apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/carissaco/devopsfinal.git
    targetRevision: main
    path: charts/bakery-backend
    helm:
      valueFiles:
        - ../values/orders.yaml
      parameters:
        - name: image.repository
          value: 014516479340.dkr.ecr.us-east-1.amazonaws.com/orders-svc
  destination:
    server: https://kubernetes.default.svc
    namespace: bakery
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
