apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/carissaco/devopsfinal.git
    targetRevision: main
    path: charts/web
    helm:
      releaseName: web
      valueFiles:
        - ../values/web-qa.yaml
      parameters:
        - name: image.repository
          value: 014516479340.dkr.ecr.us-east-1.amazonaws.com/web
  destination:
    server: https://kubernetes.default.svc
    namespace: bakery-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
